exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex("cases")
    .del()
    .then(function() {
      // Inserts seed entries
      return knex("cases").insert([{
        "caseNumber": "78-1539308",
        "bailAmount": 1711.74,
        "bail_id": 7,
        "severity": "felony",
        "violence": "violent"
      }, {
        "caseNumber": "90-0759381",
        "bailAmount": 3218.02,
        "bail_id": 14,
        "severity": "misdemeanor",
        "violence": "violent"
      }, {
        "caseNumber": "30-6459381",
        "bailAmount": 8210.73,
        "bail_id": 5,
        "severity": "misdemeanor",
        "violence": "non-violent"
      }, {
        "caseNumber": "25-3587901",
        "bailAmount": 5139.77,
        "bail_id": 3,
        "severity": "misdemeanor",
        "violence": "non-violent"
      }, {
        "caseNumber": "65-3269407",
        "bailAmount": 8108.62,
        "bail_id": 13,
        "severity": "misdemeanor",
        "violence": "violent"
      }, {
        "caseNumber": "85-0768032",
        "bailAmount": 8758.26,
        "bail_id": 12,
        "severity": "misdemeanor",
        "violence": "violent"
      }, {
        "caseNumber": "25-6400986",
        "bailAmount": 1284.64,
        "bail_id": 2,
        "severity": "felony",
        "violence": "violent"
      }, {
        "caseNumber": "89-2435915",
        "bailAmount": 2783.64,
        "bail_id": 12,
        "severity": "misdemeanor",
        "violence": "violent"
      }, {
        "caseNumber": "60-0932036",
        "bailAmount": 6787.12,
        "bail_id": 2,
        "severity": "misdemeanor",
        "violence": "violent"
      }, {
        "caseNumber": "25-4856256",
        "bailAmount": 9123.19,
        "bail_id": 9,
        "severity": "misdemeanor",
        "violence": "violent"
      }, {
        "caseNumber": "56-4129826",
        "bailAmount": 9964.43,
        "bail_id": 13,
        "severity": "misdemeanor",
        "violence": "non-violent"
      }, {
        "caseNumber": "59-2879857",
        "bailAmount": 3639.64,
        "bail_id": 11,
        "severity": "felony",
        "violence": "non-violent"
      }, {
        "caseNumber": "34-4226427",
        "bailAmount": 2711.72,
        "bail_id": 10,
        "severity": "felony",
        "violence": "violent"
      }, {
        "caseNumber": "72-9698204",
        "bailAmount": 7014.26,
        "bail_id": 1,
        "severity": "felony",
        "violence": "non-violent"
      }, {
        "caseNumber": "08-2363167",
        "bailAmount": 1353.56,
        "bail_id": 10,
        "severity": "misdemeanor",
        "violence": "non-violent"
      }, {
        "caseNumber": "93-2956124",
        "bailAmount": 4707.7,
        "bail_id": 15,
        "severity": "misdemeanor",
        "violence": "non-violent"
      }, {
        "caseNumber": "07-7807218",
        "bailAmount": 5189.64,
        "bail_id": 3,
        "severity": "felony",
        "violence": "violent"
      }, {
        "caseNumber": "44-6257024",
        "bailAmount": 1748.17,
        "bail_id": 8,
        "severity": "misdemeanor",
        "violence": "violent"
      }, {
        "caseNumber": "50-7405923",
        "bailAmount": 3036.45,
        "bail_id": 4,
        "severity": "felony",
        "violence": "non-violent"
      }, {
        "caseNumber": "57-7818368",
        "bailAmount": 1813.98,
        "bail_id": 6,
        "severity": "misdemeanor",
        "violence": "violent"
      }]);
    });
};
