exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("deragatoryMarks")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("deragatoryMarks").insert([
        {
          non_payment: false,
          fraud: false,
          skipped_bail: false,
          aggressive: false,
          hiding_fugitive: false,
          non_compliance_with_terms: true,
          no_communication: true,
          other: false,
          user_id: 2,
          on_person: 9,
        },
        {
          non_payment: false,
          fraud: true,
          skipped_bail: false,
          aggressive: true,
          hiding_fugitive: true,
          non_compliance_with_terms: true,
          no_communication: false,
          other: true,
          user_id: 4,
          on_person: 10,
        },
        {
          non_payment: false,
          fraud: false,
          skipped_bail: false,
          aggressive: false,
          hiding_fugitive: false,
          non_compliance_with_terms: true,
          no_communication: true,
          other: false,
          user_id: 1,
          on_person: 1,
        },
        {
          non_payment: false,
          fraud: false,
          skipped_bail: false,
          aggressive: true,
          hiding_fugitive: false,
          non_compliance_with_terms: false,
          no_communication: true,
          other: false,
          user_id: 2,
          on_person: 5,
        },
        {
          non_payment: false,
          fraud: false,
          skipped_bail: true,
          aggressive: true,
          hiding_fugitive: false,
          non_compliance_with_terms: false,
          no_communication: false,
          other: true,
          user_id: 3,
          on_person: 10,
        },
        {
          non_payment: true,
          fraud: true,
          skipped_bail: true,
          aggressive: false,
          hiding_fugitive: false,
          non_compliance_with_terms: true,
          no_communication: false,
          other: true,
          user_id: 4,
          on_person: 4,
        },
        {
          non_payment: false,
          fraud: true,
          skipped_bail: false,
          aggressive: true,
          hiding_fugitive: false,
          non_compliance_with_terms: true,
          no_communication: true,
          other: false,
          user_id: 5,
          on_person: 2,
        },
        {
          non_payment: false,
          fraud: false,
          skipped_bail: false,
          aggressive: false,
          hiding_fugitive: true,
          non_compliance_with_terms: true,
          no_communication: false,
          other: true,
          user_id: 4,
          on_person: 1,
        },
        {
          non_payment: false,
          fraud: false,
          skipped_bail: false,
          aggressive: false,
          hiding_fugitive: true,
          non_compliance_with_terms: true,
          no_communication: true,
          other: true,
          user_id: 3,
          on_person: 7,
        },
        {
          non_payment: false,
          fraud: true,
          skipped_bail: false,
          aggressive: false,
          hiding_fugitive: true,
          non_compliance_with_terms: false,
          no_communication: false,
          other: true,
          user_id: 4,
          on_person: 3,
        },
        {
          non_payment: true,
          fraud: false,
          skipped_bail: true,
          aggressive: true,
          hiding_fugitive: true,
          non_compliance_with_terms: false,
          no_communication: true,
          other: false,
          user_id: 2,
          on_person: 6,
        },
        {
          non_payment: true,
          fraud: true,
          skipped_bail: false,
          aggressive: true,
          hiding_fugitive: true,
          non_compliance_with_terms: false,
          no_communication: true,
          other: true,
          user_id: 1,
          on_person: 6,
        },
        {
          non_payment: false,
          fraud: false,
          skipped_bail: true,
          aggressive: false,
          hiding_fugitive: false,
          non_compliance_with_terms: true,
          no_communication: false,
          other: false,
          user_id: 5,
          on_person: 7,
        },
        {
          non_payment: false,
          fraud: false,
          skipped_bail: false,
          aggressive: true,
          hiding_fugitive: false,
          non_compliance_with_terms: false,
          no_communication: true,
          other: true,
          user_id: 2,
          on_person: 8,
        },
        {
          non_payment: false,
          fraud: true,
          skipped_bail: true,
          aggressive: true,
          hiding_fugitive: false,
          non_compliance_with_terms: false,
          no_communication: true,
          other: false,
          user_id: 1,
          on_person: 10,
        },
      ]);
    });
};
